# Bioinformatics Stronghold
# Problem dna

s = 'CAGCGTGTTACGTCTTTCCGCTGTTATCGCCGAATTCGGATCGATTGTTACTCTAAGACTGTTGGCTCAAATTGATACGTAGAATAAATGTCGTCGTAGGTCGTGCTAGGACTGTCTCGGTTGATGGTCAGGTACAGACCCGAAGTCGTCAAACAGATATTGTCAGACTGGAGCCGCTATTATGTGCCGGAAAAATAGATGACCAGGCATTACGTTCGCCGAGGGCCGGGAACGCGGGCACTCTAGGTAGGTCCAAAGGGCCCCATTACTGGTCGTTGATACTCCATCGTTTACAGGCCGGACTAAGCATCAGCAACGAGCCACTAGCCGGCGCACGGCCACAGACTCATAGCCTCAGTACAAGGCATTCTACTTCACAAAAGCTGGCACAGGTGAGGTCCGACTCGCGAGCTCCGCTGGGCCATGCGCCACTTAGACGTTGGGAACAAGGTTTGGGTCTAGAGCTGCCTTTTATTCGTAGGCTCTGATAGGCCTCATGGGGCGCACGAAGTCTGGCTCCGAAGATTAAAGTTGCCTACCAACATGCGGCTACCTTCTGCATGGCGTGCGCCAGGCCCCAATAACGGGGCGTATGCTAACCTCGAAGACAGAGGTATCCTGGCAGCTCACATGCCAGACATCCGATTGATGTATAAGACACATCCCTTAATAGACCCGAATAGGTTCTGGAGATATATCTCTTGAAGTAACGGTACGCGGCACGCTGGTTTAACTTGAAATTGAGCAGAGTGGAGCAGAAAGGCTTTACACGTCCCAGGATGCGTATAGGCGAGGTTGGGTGCGCGTGCAAACTTTAATCAATTAGCTGAGCCAGTTCAATCAATCACGTAATGAGCGGGATTCGTGGGAACACAGCAGCGTACTGGCGCTTGGTTAGACTATTGCGGTTTAGGTGTGTGGCTGTACTATTTCTTGAACGAGTTTCAATTACCGGTCCCAGGTC'
a = 0
c = 0
g = 0
t = 0
for letter in s:
    if letter == 'A':
        a = a + 1
    elif letter == 'C':
        c = c + 1
    elif letter == 'G':
        g = g + 1
    elif letter == 'T':
        t = t + 1

print(('%s %s %s %s') % (a, c, g, t))
